const Permissions = Object.freeze({
    READ_PROFILE: "READ_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    READ_SONGS: "READ_SONGS",
    CREATE_PLAYLIST: "CREATE_PLAYLIST",
    READ_PLAYLISTS: "READ_PLAYLISTS",
    UPDATE_PLAYLIST: "UPDATE_PLAYLIST",
    DELETE_PLAYLIST: "DELETE_PLAYLIST",
    DELETE_PROFILE: "DELETE_PROFILE",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT"
});

export default Permissions;
